### ISSUE TITLE
Error to import gmmreg: No module named '_extension'

### ISSUE THREAD

**Issue by tugcetasci** [bing-jian/gmmreg#4]
Hi,
after changing some line for python3 compatibility with 2to3 package (mainly print commands) and installing the package through the readme:
python setup.py build
python setup.py install

When I try to import gmmreg it gives me the following error. Would you please help me with this?

Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmmreg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/gmmreg/__init__.py", line 4, in <module>
    from ._demo import test, run_executable
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/gmmreg/_demo.py", line 10, in <module>
    from . import _core
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/gmmreg/_core.py", line 10, in <module>
    from _extension import *
ModuleNotFoundError: No module named '_extension'

**Comment by Shikherneo2** [comment]
You get this error when the build was not successfully completed. I could never make it work for Python3.

**Comment by bing-jian** [comment]
FYI,  now there is a new repo for the Python implementation of gmmreg. 
https://github.com/bing-jian/gmmreg-python
And this one should work for Python 3.  If not,  please let me know.  Thanks!

**Comment by Jorge-Quesada** [comment]
Hi, I have followed the build instructions in the new repo. The setup/install line executes without any errors, but when I try to import gmmreg I still get the 'ModuleNotFound' message:

```
>>> import gmmreg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gmmreg'

```
Is there anything I am missing? I am working with Python 3.6.9 (GCC 8.3.0).  Thanks in advance for any response!

**Comment by bing-jian** [comment]
Sorry.  Jorge-Quesada, I missed your question.  Is the problem you reported for the gmmreg-python repo or this repo?
